# Generated by Django 4.2.11 on 2026-04-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitetextoverride",
            name="value",
            field=models.TextField(blank=True),
        ),
    ]
