# Generated by Django 4.2.11 on 2026-07-27 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0003_adminactionlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_settings_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("failed_login", "Failed login"),
                            ("blocked_login", "Blocked login"),
                            ("unauthorized_api", "Unauthorized API"),
                            ("suspicious_admin", "Suspicious admin action"),
                            ("ip_blocked", "IP blocked"),
                            ("ip_unblocked", "IP unblocked"),
                            ("maintenance_on", "Maintenance enabled"),
                            ("maintenance_off", "Maintenance disabled"),
                            ("force_logout", "Force logout"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("username_attempted", models.CharField(blank=True, max_length=150)),
                (
                    "ip_address",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("user_agent", models.CharField(blank=True, max_length=400)),
                ("path", models.CharField(blank=True, max_length=300)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlockedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=64, unique=True)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocked_ips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(default="GET", max_length=10)),
                ("path", models.CharField(db_index=True, max_length=300)),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
                (
                    "ip_address",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("user_agent", models.CharField(blank=True, max_length=400)),
                ("referer", models.CharField(blank=True, max_length=400)),
                ("is_bot", models.BooleanField(db_index=True, default=False)),
                ("response_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_request_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at", "is_bot"],
                        name="common_site_created_4501ae_idx",
                    ),
                    models.Index(
                        fields=["path", "created_at"],
                        name="common_site_path_19a799_idx",
                    ),
                ],
            },
        ),
    ]
