# Generated by Django 4.2.11 on 2026-07-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_owner_monitoring_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="siterequestlog",
            name="request_bytes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="siterequestlog",
            name="response_bytes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
