# Generated by Django 4.2.11 on 2026-04-20 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="brands/")),
                ("founded_year", models.IntegerField(blank=True, null=True)),
                ("country", models.CharField(default="China", max_length=100)),
                ("website", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Brands",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField()),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("sedan", "Sedan"),
                            ("suv", "SUV"),
                            ("crossover", "Crossover"),
                            ("hatchback", "Hatchback"),
                            ("coupe", "Coupe"),
                            ("van", "Van"),
                            ("truck", "Truck"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("year_introduced", models.IntegerField()),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="cars/")),
                ("engine_type", models.CharField(blank=True, max_length=100)),
                ("horsepower", models.IntegerField(blank=True, null=True)),
                (
                    "acceleration",
                    models.CharField(
                        blank=True, help_text="0-100 km/h in seconds", max_length=50
                    ),
                ),
                (
                    "top_speed",
                    models.IntegerField(blank=True, help_text="km/h", null=True),
                ),
                (
                    "fuel_consumption",
                    models.CharField(blank=True, help_text="L/100km", max_length=50),
                ),
                ("price_range", models.CharField(blank=True, max_length=100)),
                (
                    "production_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("discontinued", "Discontinued"),
                            ("upcoming", "Upcoming"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="cars.brand",
                    ),
                ),
            ],
            options={
                "ordering": ["-year_introduced", "name"],
                "unique_together": {("brand", "name", "year_introduced")},
            },
        ),
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="cars/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="cars.carmodel",
                    ),
                ),
            ],
        ),
    ]
