# Generated by Django 4.2.11 on 2026-04-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="description_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="brand",
            name="description_pl",
            field=models.TextField(blank=True),
        ),
    ]
