# Generated by Django 4.2.11 on 2026-05-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0002_add_description_en_pl"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="brand_anecdote_en",
            field=models.TextField(
                blank=True, default="", help_text="Brand story/anecdote in English"
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="brand_anecdote_pl",
            field=models.TextField(
                blank=True, default="", help_text="Brand story/anecdote in Polish"
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="description_en",
            field=models.TextField(
                blank=True, help_text="English description (required)"
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="description_pl",
            field=models.TextField(
                blank=True, help_text="Polish description (optional but recommended)"
            ),
        ),
    ]
