# Generated by Django 4.2.11 on 2026-06-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0003_brand_brand_anecdote_en_brand_brand_anecdote_pl_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carmodel",
            name="price_range",
        ),
        migrations.AddField(
            model_name="carmodel",
            name="currency",
            field=models.CharField(
                choices=[
                    ("CNY", "¥ CNY - Chinese Yuan"),
                    ("USD", "$ USD - US Dollar"),
                    ("EUR", "€ EUR - Euro"),
                    ("GBP", "£ GBP - British Pound"),
                    ("JPY", "¥ JPY - Japanese Yen"),
                    ("PLN", "zł PLN - Polish Zloty"),
                    ("INR", "₹ INR - Indian Rupee"),
                ],
                default="CNY",
                help_text="Price currency",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="carmodel",
            name="price_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum price",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="carmodel",
            name="price_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum price",
                max_digits=12,
                null=True,
            ),
        ),
    ]
