# Generated by Django 4.2.11 on 2026-06-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0004_remove_carmodel_price_range_carmodel_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmodel",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
