# Generated by Django 4.2.11 on 2026-06-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0005_alter_carmodel_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
