# Generated by Django 4.2.11 on 2026-04-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opinions", "0002_pressreview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pressreview",
            options={"ordering": ["-is_pinned", "-published_at", "-created_at"]},
        ),
        migrations.AddField(
            model_name="pressreview",
            name="category",
            field=models.CharField(
                choices=[
                    ("test", "Test"),
                    ("news", "News"),
                    ("guide", "Guide"),
                    ("opinion", "Opinion"),
                ],
                default="test",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pressreview",
            name="internal_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pressreview",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pressreview",
            name="reading_time_minutes",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pressreview",
            name="slug",
            field=models.SlugField(blank=True, db_index=True, max_length=240),
        ),
        migrations.AddField(
            model_name="pressreview",
            name="tags",
            field=models.CharField(
                blank=True, help_text="Comma-separated tags", max_length=300
            ),
        ),
    ]
