# Generated by Django 4.2.11 on 2026-05-02 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("opinions", "0003_alter_pressreview_options_pressreview_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pressreview",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="press_reviews_authored",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
