# Generated by Django 4.2.11 on 2026-06-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opinions", "0005_opinion_category_ratings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pressreview",
            name="slug",
            field=models.SlugField(blank=True, editable=False, max_length=240),
        ),
    ]
